package com.syntacs.jobatm.WorkerService.util;

public enum GovtAuthorityList {
    UIDAI, INCOME_TAX_AUTHORITY_OF_INDIA, UTITSL, NSDL, ELECTION_COMMISSION_OF_INDIA, SSC, REVENUE_DEPARTMENT_OF_INDIA,
    RTO, NHAI, AIRPORT_AUTHORITY_OF_INDIA, INDIAN_RAILWAY,
    NCERT, CBSE, ICERT
}