package com.syntacs.jobatm.WorkerService.util;

public enum InstituteNames {
    IIT_BOMBAY, IIT_DELHI, IIT_MADRAS, IIT_KANPUR, IIT_KHARAGPUR, IISC_BANGALORE,
    BITS_PILANI, 
    UNIVERSITY_OF_MUMBAI, DELHI_UNIVERSITY, DELHI_TECHNOLOGICAL_UNIVERSITY,
    KIMS, KLE_HUBLI, BVB_HUBLI
}
