package com.syntacs.jobatm.WorkerService.util;

public enum Skill {
    CONSTRUCTION_LABOUR, CONSTRUCTION_MASONRY, RAILWAY_TRACK_REPAIRING,
    CAD_DESIGN, DATA_ENTRY, TELE_CALLING,
    MACHINE_TOOL_OPERATION, WELDING,
    BIKE_REPAIRING, CAR_REPAIRING, TRUCK_REPAIRING,
    PLUMBING, PIPE_FITTING, ELECTRICAL_WIRING,
    FASHION_DESIGN, GARMENT_STITCHING, MAKEUP_ARTISTRY,
}